# Generated by Django 3.0.7 on 2020-08-03 09:10
from __future__ import unicode_literals
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usermanagement.models

'''document link "https://simpleisbetterthancomplex.com/tutorial/2017/09/26/how-to-create-django-data-migrations.html"'''
# from usermanagement.utils.register_user import func_register_user
# from django.conf import settings
# import logging
# username=getattr(settings,'SUPERUSER')
# userpass=getattr(settings,'SUPERUSERPASS')


# def register_master(apps, schema_editor):
#     try:
#         # request_data={'name':'sueruser','email':"icaapglobaladmin@kpmg.com",'password':"superuserPass@61011"}
#         request_data={'name':'sueruser','email':username,'password':userpass}
#         resp=func_register_user(request_data)
#         logging.info('Usermanagement Master=>'+str(resp)+'done')
#         return resp['statuscode']
#     except:
#         pass



class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('usermanagement', '0009_auto_20200706_1705'),
    ]

    operations = [
        # migrations.RunPython(register_master),
        migrations.AlterField(
            model_name='accessmanagement',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LastLoginAttempt'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='last_otp_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LastOtpAttempt'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LastPasswordResetRequest'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usermanagement.Users', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='otp_attempts',
            field=models.IntegerField(default=0, verbose_name='OtpAttempts'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OtpExpiryTime'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='password_attempts',
            field=models.IntegerField(default=0, verbose_name='PasswordAttempts'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='password_reset_request_count',
            field=models.IntegerField(default=0, verbose_name='PasswordResetRequestCount'),
        ),
        migrations.AlterField(
            model_name='accessmanagement',
            name='verification_link_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VerificationLinkExpiry'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='approvalstatus',
            field=models.BooleanField(default=False, verbose_name='ApprovalStatus'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='assessment_status',
            field=models.BooleanField(default=1, verbose_name='AssessmentStatus'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='assessmentperiod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AssessmentPeriod'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='completion',
            field=models.FloatField(blank=True, null=True, verbose_name='CompletionPercentage'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedOn'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='others',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Activity', to='usermanagement.Users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='activity',
            field=models.TextField(verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ip_Address'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='timestamp',
            field=models.DateTimeField(verbose_name='TimeStamp'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.Users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fileupload', to='usermanagement.Activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedOn'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.FileField(upload_to=usermanagement.models.get_file_path, verbose_name='Datafile'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='original_file_name',
            field=models.TextField(verbose_name='OriginalFileName'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.Users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=100, verbose_name='ModuleName'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_description',
            field=models.TextField(blank=True, null=True, verbose_name='RoleDescriptions'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='RoleName'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='expiry_time',
            field=models.DateTimeField(verbose_name='ExpiryTime'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='filename',
            field=models.TextField(verbose_name='FileName'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='filepath',
            field=models.TextField(verbose_name='FilePath'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='token',
            field=models.TextField(verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.Users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.NullBooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='hashkey',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='HashKey'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(blank=True, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_verified',
            field=models.NullBooleanField(default=False, verbose_name='UserVarification'),
        ),
        migrations.AlterModelTable(
            name='accessmanagement',
            table='AccessManagement',
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='FileUpload',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='Roles',
        ),
        migrations.AlterModelTable(
            name='temporaryurl',
            table='TemporaryUrl',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
